let products = [
  {
    id: 1,
    name: "Ahmed Shirt",
    price: "45",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-1.jpg",
  },
  {
    id: 2,
    name: "Ali Shirt",
    price: "30",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-2.jpg",
  },
  {
    id: 3,
    name: "Emad Shirt",
    price: "100",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-3.jpg",
  },
  {
    id: 4,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-4.jpg",
  },
  {
    id: 5,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-5.jpg",
  },
  {
    id: 6,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-6.jpg",
  },
  {
    id: 7,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-7.jpg",
  },
  {
    id: 8,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-8.jpg",
  },
  {
    id: 9,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-9.jpg",
  },
  {
    id: 10,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-10.jpg",
  },
  {
    id: 11,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-11.jpg",
  },
  {
    id: 12,
    name: "Amr Shirt",
    price: "40",
    desc: "Lorem ipsum dolor sit amet consectetur,adipisicing elit",
    img: "images/img-12.jpg",
  },
];
